services:
  web:
    build: .
    ports: ["8080:80"]
    volumes: [ "./:/var/www/html" ]

  ui:
    image: node:20-alpine
    working_dir: /app
    volumes: 
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npx tailwindcss -i ./public/assets/css/input.css -o ./public/assets/css/tailwind.css --watch --minify"
    restart: unless-stopped
    stdin_open: true
    tty: true